version: '3.8'

services:

  finance-module:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: finance-module
    networks:
      - finance-module-network
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__FinanceModuleDb=Server=finance-db;Database=db_finance;User Id=sa;Password=MicroUser123!;TrustServerCertificate=True;
    volumes:
      - ./FinanceModule/src:/app
      - finance-module-bin:/app/bin  
      - finance-module-obj:/app/obj
    working_dir: /app
    command: dotnet watch run --urls "http://+:8080" --non-interactive --restart-on-rude-edit
    depends_on:
      - finance-db


  finance-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: finance-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MicroUser123!
    ports:
      - "1434:1433"
    networks:
      - finance-module-network
    volumes:
    - finance-mssql-db:/var/opt/mssql
    

volumes:
    finance-module-bin:
    finance-module-obj:
    finance-mssql-db:
    
    
networks:
    finance-module-network:
        external: true