version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
        - project_micro_network
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq


  redis:
    image: redis:7-alpine
    container_name: redis
    ports: 
    - "6379:6379"
    networks:
    - project_micro_network
    restart: always
        

volumes:
    rabbitmq_data:
    
    
networks:
    project_micro_network:
        external: true