version: "3.8"

services: 

    survey-module:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        container_name: survey-module
        networks: 
            - survey-module-network
        ports:
            - "5002:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8080 
            - ConnectionStrings__SurveyModuleDb=Server=survey-db;Database=db_survey;User Id=sa;Password=MicroUser123!;TrustServerCertificate=True;
        volumes:
            - ./SurveyModule/src:/app
            - survey-module-bin:/app/bin  
            - survey-module-obj:/app/obj
        working_dir: /app
        command: dotnet watch run --urls "http://+:8080"
        depends_on:
            - survey-db
            
    survey-db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: survey-db
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=MicroUser123!
        ports:
          - "1435:1433"
        networks:
          - survey-module-network
        volumes:
          - survey-mssql-db:/var/opt/mssql
        
        

volumes:
    survey-module-bin:
    survey-module-obj:
    survey-mssql-db:
    
    
networks:
    survey-module-network:
        external: true